/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CREATE_UNIVERSITY;

import START.First_Program;
import java.io.*;
import java.sql.*;
import javax.swing.JOptionPane;


public class Academic_Curriculum extends javax.swing.JFrame {

    /**
     * Creates new form Academic_Curriculum
     */
    Connection conn = null;
    PreparedStatement ps = null;
    Statement s = null;
    ResultSet r = null;
    
    
    public Academic_Curriculum() {
        
        conn = First_Program.First_Program();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        aca_uni = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        aca_fac = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        aca_dept = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        sem = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        course = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACADEMIC_COURSE_CURRICULUM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 0, 14))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel27.setText("University Name:");

        aca_uni.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        aca_uni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aca_uniMouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel39.setText("Faculty:");

        aca_fac.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        aca_fac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aca_facMouseClicked(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel40.setText("Department:");

        aca_dept.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        aca_dept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aca_deptMouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel41.setText("Semester:");

        sem.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel42.setText("COURSES:");

        course.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jButton5.setFont(new java.awt.Font("Algerian", 3, 40)); // NOI18N
        jButton5.setText("insert");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aca_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aca_uni, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aca_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(460, 460, 460))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aca_uni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aca_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aca_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jButton3.setFont(new java.awt.Font("Algerian", 0, 40)); // NOI18N
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Algerian", 0, 40)); // NOI18N
        jButton2.setText("next");

        jButton1.setFont(new java.awt.Font("Algerian", 0, 40)); // NOI18N
        jButton1.setText("exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 185, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aca_uniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aca_uniMouseClicked
        // TODO add your handling code here:
        try {
            String sql, l;
            sql = "SELECT FULL_NAME FROM OFFICIAL_INFORMATION";

            //s = conn.createStatement();
            aca_uni.removeAllItems();

            ps = conn.prepareStatement(sql);
            r = ps.executeQuery(sql);

            while (r.next()) {
                l = r.getString("FULL_NAME");
                aca_uni.addItem(l);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_aca_uniMouseClicked

    private void aca_facMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aca_facMouseClicked
        // TODO add your handling code here:
         try {

            String sql, l, uni_name, id = null;

            uni_name = aca_uni.getSelectedItem().toString();

            sql = "SELECT UNI_ID FROM OFFICIAL_INFORMATION WHERE FULL_NAME = ?";

            ps = conn.prepareStatement(sql);
            ps.setString(1, uni_name);
            r = ps.executeQuery();
            while (r.next()) {
                id = r.getString("UNI_ID");
            }

            aca_fac.removeAllItems();

            sql = "SELECT FACULTY_NAME FROM FACULTY WHERE UNI_ID = ?";

            ps = conn.prepareStatement(sql);
            ps.setString(1, id);
            r = ps.executeQuery();

            while (r.next()) {
                l = r.getString("FACULTY_NAME");
                aca_fac.addItem(l);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_aca_facMouseClicked

    private void aca_deptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aca_deptMouseClicked
        // TODO add your handling code here:
        try {

            String sql, l, uni_name, fac_name, id = null, fac_id = null;

            uni_name = aca_uni.getSelectedItem().toString();
            fac_name = aca_fac.getSelectedItem().toString();

            sql = "SELECT UNI_ID FROM OFFICIAL_INFORMATION WHERE FULL_NAME = ?";

            ps = conn.prepareStatement(sql);
            ps.setString(1, uni_name);
            r = ps.executeQuery();
            while (r.next()) {
                id = r.getString("UNI_ID");
            }
            
            //aca_fac.removeAllItems();
            
            sql = "SELECT FACULTY_ID FROM FACULTY WHERE FACULTY_NAME = ?";
            
            ps = conn.prepareStatement(sql);
            ps.setString(1, fac_name);
            r = ps.executeQuery();
            
            while (r.next())
            {
                fac_id = r.getString("FACULTY_ID");                
            }


            aca_dept.removeAllItems();

            sql = "SELECT DEPARTMENT_NAME FROM DEPARTMENT WHERE FACULTY_ID = ?";

            ps = conn.prepareStatement(sql);
            ps.setString(1, fac_id);
            r = ps.executeQuery();

            while (r.next()) {
                l = r.getString("DEPARTMENT_NAME");
                aca_dept.addItem(l);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_aca_deptMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        try {

            String sql, uni_name, Faculty, Dept,  dept_id = null;

            uni_name = aca_uni.getSelectedItem().toString();
            Faculty = aca_fac.getSelectedItem().toString();
            Dept = aca_dept.getSelectedItem().toString();
            //I had to do this.

            sql = "SELECT DEPARTMENT_ID FROM DEPARTMENT  WHERE DEPARTMENT_NAME = '" +Dept+ "'"  ;
            
            ps = conn.prepareStatement(sql);
            r = ps.executeQuery();
            while (r.next()){
                dept_id = r.getString("DEPARTMENT_ID");
            }

            sql = "INSERT INTO ACADEMIC_CURRICULUM (COURSE, SEMESTER, DEPARTMENT_ID) "
                    + "VALUES (?, ?, ?)";


            ps = conn.prepareStatement(sql);
            ps.setString(1, course.getText().toUpperCase());
            ps.setString(2, sem.getSelectedItem().toString());
            ps.setString(3, dept_id);


            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data saved Successfully");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new University().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Academic_Curriculum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Academic_Curriculum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Academic_Curriculum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Academic_Curriculum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Academic_Curriculum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aca_dept;
    private javax.swing.JComboBox<String> aca_fac;
    private javax.swing.JComboBox<String> aca_uni;
    private javax.swing.JTextField course;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox<String> sem;
    // End of variables declaration//GEN-END:variables
}
